export {
  universities,
  programs,
  mentors,
  students,
  sessions,
  reviews,
  conversations,
  earnings,
  applications,
  mentorStats,
  studentStats,
} from "./storage";

export const universityCompareData = {
  "uet-lahore": {
    closingMerits: {
      "BS Computer Science": 82.5,
      "BS Electrical Engineering": 82.6,
      "BS Mechanical Engineering": 81.38,
      "BS Civil Engineering": 79.85,
      "BS Chemical Engineering": 78.7,
      "BS Software Engineering": 78.0,
      "BS Data Science": 77.5,
    },
    admissionFee: 1800,
    semesterFee: 79000,
    totalFourYearCost: 660000,
    hostelStatus: "Available — Not guaranteed. Merit-based application. Priority to outstation students. PKR 12,000–18,000/semester.",
    entryTests: ["ECAT"],
    topSectors: ["WAPDA", "NESPAK", "Jazz", "Ufone", "Systems Limited", "NetSol", "Engro Powergen"],
    freshGradSalary: "PKR 80,000–200,000/month",
    knownFor: ["Civil Engineering", "Electrical Engineering", "Mechanical Engineering", "Computer Science", "KICS AI Research"],
    qsRank: "801–850",
    employmentRank: "Top 5 in Pakistan",
    pecAccredited: true,
    researchProjects: 19,
  },
  "nust-islamabad": {
    closingMerits: {
      "BS Computer Science": 79.11,
      "BS Software Engineering": 78.42,
      "BS Electrical Engineering": 72.0,
      "BS Mechanical Engineering": 71.0,
      "BS Chemical Engineering": 70.0,
      "BS Civil Engineering": 70.0,
      "BBA": 65.0,
      "BS Economics": 67.0,
    },
    admissionFee: 35000,
    semesterFee: 140000,
    totalFourYearCost: 2240000,
    hostelStatus: "Available — Outstation students prioritized. First come first served after first merit list. PKR 16,000/month single room.",
    entryTests: ["NET"],
    topSectors: ["Google", "Microsoft", "Amazon", "Systems Limited", "i2c", "PAF", "NESCOM", "McKinsey", "Unilever"],
    freshGradSalary: "PKR 100,000–500,000/month",
    knownFor: ["Software Engineering", "CS & AI", "Aerospace Engineering", "Electrical Engineering", "NSTP Science Park"],
    qsRank: "371",
    employmentRank: "#2 in Pakistan",
    pecAccredited: true,
    researchProjects: 1550,
  },
  "pu-lahore": {
    closingMerits: {
      "BS Computer Science": 82.0,
      "BS Software Engineering": 80.0,
      "BS Information Technology": 77.0,
      "BS Electrical Engineering": 80.0,
      "BS Civil Engineering": 77.0,
      "BS Chemical Engineering": 75.0,
      "BS Mathematics": 72.0,
      "BS Psychology": 74.0,
      "BS Economics": 76.0,
      "LLB": 72.0,
    },
    admissionFee: 7500,
    semesterFee: 30000,
    totalFourYearCost: 240000,
    hostelStatus: "Available — 28 hostels (17 male, 11 female). Outstation students prioritized. PKR 10,000–18,000/semester.",
    entryTests: ["PU-E", "PU-M", "PU-AHS", "PU-COM", "PU-CSP"],
    topSectors: ["CSS/PCS Civil Service", "HBL", "UBL", "Systems Limited", "NetSol", "UNDP", "Lahore Courts"],
    freshGradSalary: "PKR 50,000–150,000/month",
    knownFor: ["Social Sciences", "Law", "Pharmacy", "PUCIT Computer Science", "Mathematics", "Largest Alumni Network"],
    qsRank: "542",
    employmentRank: "#1 in Pakistan (QS Employment Outcomes)",
    pecAccredited: true,
    researchProjects: 138,
  },
};
